#!/bin/sh


COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

echo 提交訊息:
cat $COMMIT_MSG_FILE
COMMIT_MSG=`cat $COMMIT_MSG_FILE`
echo 


COMMIT_MSG=$(echo "$COMMIT_MSG" | {
    while IFS= read -r line; do

		if [[ "$line" =~ ^(\#)+.*$ ]]
		then
			echo $line
		else

			if [[ "$line" == "Body" ]]
			then
			    echo 
			else
			    echo "$line"
			fi

		fi

    done 
})
echo "$COMMIT_MSG" > $COMMIT_MSG_FILE


if [[ "$COMMIT_MSG" =~ ^(fix|feat|perf|refactor|chore|style|test):[[:space:]]+.*$ ]] || [[ "$COMMIT_MSG" =~ ^Merge[[:space:]]branch[[:space:]] ]] || [[ "$COMMIT_MSG" =~ ^Merge[[:space:]]remote-tracking[[:space:]]branch ]] || [[ "$COMMIT_MSG" =~ ^Merge[[:space:]]commit[[:space:]] ]] || [[ "$COMMIT_MSG" =~ ^Revert[[:space:]]"" ]]; then
    echo
	echo "成功: 格式正確."
else
	cat <<EOF
錯誤: 格式不正確.

EOF
	exit 1
fi






